<?php

/**
 * @file
 * Module file for UTEvent listing page.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\utevent_view_listing_page\Form\ListingPageConfig;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_FORM_ID_alter() for the general config form.
 */
function utevent_view_listing_page_form_utevent_general_config_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter the general config form to include an the listing page title.
  \Drupal::classResolver(ListingPageConfig::class)->alterForm($form, $form_state, $form_id);
}
