<?php

/**
 * @file
 * Event import installation file.
 */

use Drupal\utevent\Permissions;

/**
 * Implements hook_install().
 */
function utevent_import_install() {

  $roles = Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  /** @var Drupal\user\Entity\Role $role */
  foreach ($roles as $role_id => $role) {
    $role_permissions = $role->getPermissions();
    foreach ($role_permissions as $permission) {
      if ($permission == 'administer utevent') {
        Permissions::assignPermissions('manager', $role_id);
        Drupal::messenger()->addMessage(t('Feeds permissions set for %role role.', [
          '%role' => $role->label(),
        ]));
      }
    }
  }

}
