utevent_view_listing_page.config:
  type: config_entity
  label: 'UTEvent Listing Page Configuration'
  mapping:
    page_title:
      type: string
      label: 'Page Title'
    display_past_events:
      type: int
      label: 'Display past events'
    display_calendar:
      type: int
      label: 'Display calendar'
